[book]
authors = ["olivier de Meringo", "Boavizta"]
language = "en"
multilingual = false
src = "src"
title = "Boavizta cloud scanner ðŸ“¡"

# Deactivate link checker by default
# cargo install mdbook-linkcheck
# [output.linkcheck]