name: test suite
on: [push, pull_request]

jobs:
  clippy:
    name: cargo clippy and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components:  clippy
      - run: cargo clippy
      - run: cargo test --all-features


  # test:
  #   name: cargo test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dtolnay/rust-toolchain@stable
  #     - run: cargo test --all-features
